server:
  port: 31200
spring:
  application:
    name: xc-service-manage-course
  data:
    mongodb:
      uri:  mongodb://root:root@localhost:27017
      database: xc_cms
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/xc_course?characterEncoding=utf-8
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
#配置eureka
eureka:
  client:
    register-with-eureka: true #向eureka中注册服务
    fetch-registry: true # 发现服务
    service-url:
      #defaultZone: ${EUREKA_SERVER:http://localhost:50101/eureka/,http://localhost:50102/eureka/}
      defaultZone: http://localhost:50101/eureka/
  instance:
    prefer-ip-address: true # 将自己的ip地址注册到Eureka服务中
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id: ${spring.application.name}:${server.port} #指定实例id
  #配置ribbon
ribbon:
  MaxAutoRetries: 2 # 最大重试次数,当eureka中可以找到服务,但是服务连接不上时将会重试
  MaxAutoRetriesNextServer: 3 # 切换势力的重复次数
  OkToRetryOnAllOperations: false # 将对所有请求都进行重试,如果是get则可以,如果是post、post等操作，在没有设置幂等性的情况下很危险，所以设置为false
  ConnectionTimeout: 5000 # 请求连接的超时时间
  ReadTimeout: 6000 # 请求处理的超时时间
course-publish:
  siteId: 5a751fab6abb5044e0d19ea1
  templateId: 5aec5dd70e661808240ab7a6
  previewUrl: http://www.xuecheng.com/cms/preview/
  pageWebPath: /course/detail/
  pagePhysicalPath: /course/detail/
  dataUrlPre: http://localhost:31200/course/courseview/
pagehelper:
  helper-dialect: mysql